---
abstract: 'Extract URLs from text'
author:
  - unknown
build_requires: {}
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: grepurl
no_index:
  directory:
    - t
    - inc
resources:
  repository: https://github.com/briandfoy/grepurl
version: 1.02
